name: plural_lint
description: A sample command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.3
  petitparser: ^5.4.0
  xml: ^6.3.0
  path: ^1.8.3
  meta: ^1.9.1
  resource_portable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
