name: plural_lint
description: >
  Plural_lint is a developer tool to check plural translations in your project.
  It detects both missing and unused plural quantities in the ARB files.
version: 0.0.8
repository: https://github.com/koral--/plural_lint
issue_tracker: https://github.com/koral--/plural_lint/issues
topics:
    - lint
    - check
    - internationalization
    - static-code-analysis
    - i18n

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.0
  petitparser: ^6.0.1
  xml: ^6.3.0
  path: ^1.8.3
  meta: ^1.9.1
  resource_portable: ^3.1.0

dev_dependencies:
  test: ^1.24.8
  lints: ^3.0.0
  custom_lint: ^0.5.4
  flutter:
    sdk: flutter
    
